services:
  backend:
    image: msouza1314/simple-fortune-cookie:backend
    ports: 
     - 9000:9000
  frontend:
    image: msouza1314/simple-fortune-cookie:frontend
    ports:
     - 8080:8080
    environment:
      BACKEND_DNS: 172.17.0.1